[project]
name = "fastapi-cam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.2",
    "opencv-contrib-python>=4.12.0.88",
]
